"""
Bonus - Report Rendering

Combines Task 1A + 1B outputs into a one-page equity research brief,
rendered as styled HTML with an embedded matplotlib chart (base64 PNG).
"""
from __future__ import annotations

import base64
import io
from datetime import datetime

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt


def _chart_to_base64(ohlcv_df, ticker: str) -> str:
    fig, ax = plt.subplots(figsize=(9, 4))
    ax.plot(ohlcv_df.index, ohlcv_df["Close"], label="Close", linewidth=1.2)
    if "SMA_50" in ohlcv_df:
        ax.plot(ohlcv_df.index, ohlcv_df["SMA_50"], label="SMA 50", linewidth=1)
    if "SMA_200" in ohlcv_df:
        ax.plot(ohlcv_df.index, ohlcv_df["SMA_200"], label="SMA 200", linewidth=1)
    if "BB_upper" in ohlcv_df and "BB_lower" in ohlcv_df:
        ax.fill_between(ohlcv_df.index, ohlcv_df["BB_lower"], ohlcv_df["BB_upper"],
                         alpha=0.15, label="Bollinger Bands")
    ax.set_title(f"{ticker} - Price & Technical Overlay")
    ax.legend(loc="upper left", fontsize=8)
    ax.set_xlabel("Date")
    ax.set_ylabel("Price")
    fig.tight_layout()

    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=130)
    plt.close(fig)
    buf.seek(0)
    return base64.b64encode(buf.read()).decode("utf-8")


def render_report(
    ticker: str,
    summary,
    headline_sentiments: list,
    aggregate_sentiment,
    trade_signal,
    ohlcv_df,
) -> str:
    chart_b64 = _chart_to_base64(ohlcv_df, ticker)
    top_headlines = headline_sentiments[:3]
    headline_rows = "".join(
        f"<li><b>[{h.sentiment.upper()}]</b> {h.headline} "
        f"<span class='conf'>(confidence {h.confidence:.2f})</span></li>"
        for h in top_headlines
    )
    signal_color = {"Buy": "#1a7f37", "Sell": "#c92a2a", "Hold": "#8a6d00"}.get(
        trade_signal.signal if trade_signal else "Hold", "#333"
    )

    html = f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{ticker} Equity Research Brief</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 780px;
          margin: 40px auto; color: #1a1a1a; line-height: 1.5; }}
  h1 {{ font-size: 26px; border-bottom: 2px solid #222; padding-bottom: 8px; }}
  h2 {{ font-size: 17px; margin-top: 28px; color: #222; }}
  .meta {{ color: #666; font-size: 13px; }}
  .grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin: 16px 0; }}
  .card {{ background: #f6f7f9; border-radius: 8px; padding: 12px; text-align: center; }}
  .card .label {{ font-size: 11px; color: #666; text-transform: uppercase; }}
  .card .value {{ font-size: 18px; font-weight: 600; }}
  .signal {{ font-size: 22px; font-weight: 700; color: {signal_color}; }}
  .conf {{ color: #888; font-size: 12px; }}
  .disclaimer {{ margin-top: 32px; font-size: 12px; color: #888; border-top: 1px solid #ddd;
                 padding-top: 12px; }}
  img {{ max-width: 100%; border-radius: 8px; margin: 12px 0; }}
</style>
</head>
<body>
  <h1>{ticker} Equity Research Brief</h1>
  <div class="meta">Generated {datetime.now().strftime('%Y-%m-%d %H:%M')} &middot; Automated first-pass analysis</div>

  <h2>Company Snapshot</h2>
  <div class="grid">
    <div class="card"><div class="label">Current Price</div><div class="value">${summary.current_price:.2f}</div></div>
    <div class="card"><div class="label">52W Range</div><div class="value">${summary.fifty_two_week_low:.2f} - ${summary.fifty_two_week_high:.2f}</div></div>
    <div class="card"><div class="label">YTD Return</div><div class="value">{summary.ytd_return_pct:.1f}%</div></div>
    <div class="card"><div class="label">P/E Ratio</div><div class="value">{summary.pe_ratio if summary.pe_ratio else 'N/A'}</div></div>
    <div class="card"><div class="label">Momentum</div><div class="value">{summary.momentum_signal}</div></div>
    <div class="card"><div class="label">News Sentiment</div><div class="value">{aggregate_sentiment.overall_score:+.2f}</div></div>
  </div>

  <h2>Technical Outlook</h2>
  <img src="data:image/png;base64,{chart_b64}" alt="Price chart">

  <h2>News Sentiment Summary</h2>
  <p>{aggregate_sentiment.positive_count} positive / {aggregate_sentiment.negative_count} negative /
     {aggregate_sentiment.neutral_count} neutral out of {aggregate_sentiment.total_headlines} headlines analysed.</p>
  <ul>{headline_rows}</ul>

  <h2>LLM Recommendation</h2>
  <p class="signal">{trade_signal.signal if trade_signal else 'N/A'}</p>
  <p>{trade_signal.justification if trade_signal else 'Signal generation failed validation.'}</p>

  <div class="disclaimer">
    <b>Risk Disclaimer:</b> This report is generated by an automated research
    pipeline for demonstration purposes only. It does not constitute financial
    advice, and should not be relied upon for investment decisions. Past
    performance and technical indicators are not reliable predictors of future
    returns. Consult a licensed financial advisor before trading.
  </div>
</body>
</html>
"""
    return html
